<?php

define('FADING_BANNER_ICE', 'isbanen');
define('FADING_BANNER_SKOJTEHAL', 'skojtehal');

/**
 * Implementation of hook_menu().
 */
function fading_banner_menu() {
  $items['banner/%/data.xml'] = array(
    'page callback' => '_fading_banner_xml',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Generates xml output for the flash banner as a menu-callback.
 *
 * @param string $type
 */
function _fading_banner_xml($type) {
  drupal_set_header('Content-Type: text/xml; charset=utf-8');
  echo '<?xml version="1.0" encoding="utf-8"?>
        <data delay="4000">
          <frontImage>/sites/all/modules/custom/fading_banner/img/front.png</frontImage>
          ' ._fading_banner_get_images_link($type). '
        </data>';
}

/**
 * Generates image links for xml output
 *
 * @param string $type
 * @return string $str
 *    Images link of type given
 */
function _fading_banner_get_images_link($type) {
  $str = '';
  $statement = 'SELECT filepath
                FROM files
                WHERE fid IN (SELECT field_fading_banner_fid AS fid
                              FROM content_type_fading_banner
                              WHERE field_association_value = \'%s\')';
  $query = db_query($statement, ($type == FADING_BANNER_SKOJTEHAL ? 'Skøjtehallen' : 'Isbanen'));
  while ($row = db_fetch_array($query)) {    
     $str .= '<img>/' .$row['filepath']. '</img>';
  }

  return $str;
}

/**
 * Implementation of hook_init
 */
function fading_banner_init() {
  drupal_add_js(drupal_get_path('module', 'fading_banner') .'/js/swfobject.js');
}

/**
 * Implmentation of hook_theme. Make 'fading_banner' theme function visible.
 *
 * @return array
 */
function fading_banner_theme() {
  return array(
    'fading_banner' => array(
      'arguments' => array('id' => NULL, 'image' => NULL),
    ),
  );
}

/**
 * Theme fading banner block content.
 *
 */
function theme_fading_banner($id, $flash_location) {
  drupal_add_js('var flashvars = {
                        xmlPath: "/banner/'. $id .'/data.xml"
                 };
		 var params = {
			menu: "false",
			scale: "noScale",
			allowFullscreen: "false",
			allowScriptAccess: "always",
			bgcolor: "#FFFFFF",
                        wmode: "transparent"
		 };
		 var attributes = {
			id: "fading_banner_'. $id .'"
		 };
		 swfobject.embedSWF("/'. $flash_location .'/banner.swf",
                                    "altContent",
                                    "100%", "188px",
                                    "9.0.0",
                                    "/'. $flash_location .'/expressInstall.swf",
                                    flashvars,
                                    params,
                                    attributes);', 'inline');
  
  $output = '<div id="altContent">
		<p><a href="http://www.adobe.com/go/getflashplayer"><img
			src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif"
			alt="Get Adobe Flash player" /></a></p>
	     </div>';
  
  return $output;
}

/**
 * Implementation of hook_block
 */
function fading_banner_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case "list":
      $blocks[0]['info'] = t('Skøjtehallen');
      $blocks[0]['cache'] = BLOCK_NO_CACHE;

      $blocks[1]['info'] = t('Isbanen');
      $blocks[1]['cache'] = BLOCK_NO_CACHE;

      return $blocks;
      break;

    case "view":
      if ($delta == 0) {
        // Skøjtehallen is begin displayed
        $block['subject'] = t('Skøjtehallen');
        $block['content'] = theme('fading_banner', FADING_BANNER_SKOJTEHAL, drupal_get_path('module', 'fading_banner'));
      }
      elseif ($delta == 1) {
        // Isbanen is begin displayed
        $block['subject'] = t('Isbanen');
        $block['content'] = theme('fading_banner', FADING_BANNER_ICE, drupal_get_path('module', 'fading_banner'));
      }

      return $block;
      break;
  }
}